# Generated by Django 5.0 on 2023-12-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_booking_user_customer_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('cancel_booking', 'Can Cancel Booking')]},
        ),
    ]
