# Generated by Django 5.0 on 2023-12-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('cancel_booking', 'Can Cancel booking')]},
        ),
    ]
