# Generated by Django 5.0 on 2023-12-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
