# Generated by Django 5.0 on 2023-12-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
