# Generated by Django 5.0 on 2023-12-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_remove_car_status_car_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='availability',
            new_name='availabile',
        ),
    ]
