# Generated by Django 5.0 on 2023-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_auto_20231228_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
