# Generated by Django 5.0 on 2024-01-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        ('review', '0003_review_rating'),
    ]

    operations = [
    ]
